### ISSUE TITLE
Don't export DEBIAN_FRONTEND, DEBCONF_NONINTERACTIVE_SEEN, etc. in brickstrap shell

### ISSUE THREAD

**Issue by dlech** [ev3dev/brickstrap#25]
We are currently setting...

    export DEBIAN_FRONTEND=noninteractive
    export DEBCONF_NONINTERACTIVE_SEEN=true
    export LC_ALL=C LANGUAGE=C LANG=C
    export PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin

...globally these are needed for the configure-rootfs and run-hooks steps. It probably doesn't hurt for other steps, but it is not good to have these set for brickstrap shell.

**Comment by cmacq2** [comment]
Worth noting: the `PATH` export may also be required for some other parts of brickstrap. We may be using tools from `sbin` paths already. A recent example is: `/usr/sbin/update-binfmts` (though I hardcoded that path). So the path export in particular needs careful review before moving it elsewhere.

**Comment by cmacq2** [comment]
Worth noting that in particular `multistrap` is also located in `/usr/sbin`.

**Comment by dlech** [comment]
no longer applicable
