### ISSUE TITLE
delete command does not delete the <dest> directory

### ISSUE THREAD

**Issue by dlech** [ev3dev/brickstrap#34]
Now that all of the generated files live under one directory, the `delete` command should `rm -rf` that directory.

**Comment by dlech** [comment]
If the `-d` option is not specified, the dest directory is `$(pwd)`. In that case, `rm -f *` would make more sense. @cmacq2, what is the best way to tell if `-d` was specified or not?

**Comment by cmacq2** [comment]
That's actually the wrong approach. What you should do is check whether `$(pwd)` is at or underneath `$(br_dest_dir)`.  Because if you delete the current working directory the shell can get cranky...

**Comment by cmacq2** [comment]
Since PR #44  is now merged, this issue can probably be closed.
