### ISSUE TITLE
Not found option 

### ISSUE THREAD

**Issue by Svjatogor** [ev3dev/brickstrap#58]
I get error, when I builded an image
![2016-07-26 13-20-04](https://cloud.githubusercontent.com/assets/11637112/17134562/b24fca10-5333-11e6-8fd4-ca233c5e8998.png)

**Comment by dlech** [comment]
The command line options have changed. Try...

    brickstrap -p ev3dev-jessie -c ev3 -d ev3-rootfs create-rootfs

After that the `-p` and `-c` options are not needed. For example...

    brickstrap -d ev3-rootfs shell

...or...

    cd ev3-rootfs
    brickstrap shell

**Comment by Svjatogor** [comment]
Thanks you. I found it
