### ISSUE TITLE
Image dont boot into Brick

### ISSUE THREAD

**Issue by puedesleerlo** [ev3dev/brickstrap#65]
Hello everyone, I was working with the docker image ev3dev/debian-jessie-cross, and I made a Dockfile, etc. The container works ok but when I use brickstrap for turning my docker image into a booteable, the image dont boot into the brick. All the process of burn the image into an SD card is normal, without errors.

Thank you!

**Comment by dlech** [comment]
You need to use ev3dev/ev3dev-jessie-ev3-generic (or if you are going for minimal, ev3dev/ev3dev-jessie-ev3-base) as a base to create a bootable image. ev3dev/debian-jessie-cross is for cross-compiling and is missing critical components for booting, like the kernel.
