### ISSUE TITLE
Can't Sudo inside Docker Containers

### ISSUE THREAD

**Issue by keenanjohnson** [ev3dev/brickstrap#69]
I ran the setup to get the docker containers configured, but I can't seem to run sudo.

I get the following

no tty present and no askpass program specified docker

**Comment by dlech** [comment]
You need to run docker with the `--tty` option.

**Comment by keenanjohnson** [comment]
Hmmm running the command below didn't seem to resolve that. I still get the same no tty error.

Keenans-MBP:~ keenan$ docker run --tty --rm -it ev3dev/ev3dev-buster-ev3-generic su -l robot

**Comment by dlech** [comment]
Try this to get a command prompt inside of the docker container: 

     docker run --tty --rm -it ev3dev/ev3dev-buster-ev3-generic bash

but be aware that when you exit, all changes are lost because of the `--rm` option.

**Comment by dlech** [comment]
also, `--tty` is the same as `t` in `-it`
