### ISSUE TITLE
WSL 2 integration of Docker Desktop

### ISSUE THREAD

**Issue by HWiese1980** [ev3dev/brickstrap#71]
Hey folks,

installation via `apt-get` is pretty straight forward and easy, however, it has some dependencies that, in a WSL 2 environment with a recent Docker Desktop version installed on Windows and integrated in the WSL 2 distro, are already provided by Docker Desktop. Installing the script from github is of course possible, though less simple than just doing apt install. Do you think it might me a good idea to provide a way to install it without the dependencies? Like e.g. `sudo apt-get install brickstrap-wsl2` or something? Just my two cents...

Keep rocking!

**Comment by HWiese1980** [comment]
Haven't tried it yet, because after some deeper research it seems like brickstrap has diverged from my needs, which is using it to cross compile for the EV3. It looks like there are now some dedicated docker containers for this exact purpose, according to this page: https://www.ev3dev.org/docs/tutorials/. Is that correct?

**Comment by dlech** [comment]
Yes, the docker cross-compile images are the way to go now.

**Comment by HWiese1980** [comment]
Thank you. In this case I think we can close this issue.
