### ISSUE TITLE
When I tried to install brickstrap i found an issue related to adding repository

### ISSUE THREAD

**Issue by ariharasudhanm** [ev3dev/brickstrap#72]
On my EV3 i tried to install brickstrap following the command to add the repository for ev3dev using ' sudo add-apt-repository ppa:ev3dev/tools'  I am getting this issue called 'Error: could not find a distribution template for ev3dev/stretch'.

**Comment by dlech** [comment]
Brickstrap does not run on the EV3, you need to run in on a computer or virtual machine running Ubuntu 18.04.

**Comment by ariharasudhanm** [comment]
Thank you for your reply in mean time and I want to whether we can install brickstrap in ubuntu 16.04?

**Comment by dlech** [comment]
Yes, I think that should still work.

**Comment by ariharasudhanm** [comment]
Hope it works. Thank you.
